const Students = () =>{
    return (
        <div>
            <h2>Student Information Page</h2>
        </div>
    );
}
export const metadata = {
    title: "Student Information",
    description: "Generated by create next app",
  };

export default Students;